# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f60c685bd1bb2f67d24f62bfe281f9ce3a9932ea8f63924e0f1fa53b180b7bbfc7f6a7193439792d940eb49f1660ebe4cb976e91ac940071445ebe32c2eefd

test:
  secret_key_base: bb2f5c4ed1b4e1366190ecd8926b43dd525db374353d255bab4c2ef3997acf9851ffe0a0f36f1e014e3d99c4900ceeb76c86335a875623bb0c4a2fe304560203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
